### ISSUE TITLE
Temporal Dependencies

### ISSUE THREAD

**Issue by davekerber** [joist-orm/joist-orm#1078]
Somewhere between version 1.161.2 and 1.164.1 new temporal dependencies were added and I get these build errors: 

```sh
npm run test../../../node_modules/joist-orm/build/utils.d.ts:1:56 - error TS2307: Cannot find module 'temporal-polyfill' or its corresponding type declarations.

1 import type { Intl, Temporal, toTemporalInstant } from "temporal-polyfill";
                                                         ~~~~~~~~~~~~~~~~~~~

../../../node_modules/joist-orm/build/serde.d.ts:1:31 - error TS2307: Cannot find module 'temporal-polyfill' or its corresponding type declarations.

1 import type { Temporal } from "temporal-polyfill";
                                ~~~~~~~~~~~~~~~~~~~

../../../node_modules/joist-orm/build/newTestInstance.d.ts:24:42 - error TS2307: Cannot find module 'temporal-spec' or its corresponding type declarations.

24 export declare let testPlainDate: import("temporal-spec").Temporal.PlainDate | undefined;
                                            ~~~~~~~~~~~~~~~

../../../node_modules/joist-orm/build/newTestInstance.d.ts:25:46 - error TS2307: Cannot find module 'temporal-spec' or its corresponding type declarations.

25 export declare let testPlainDateTime: import("temporal-spec").Temporal.PlainDateTime | undefined;
                                                ~~~~~~~~~~~~~~~

../../../node_modules/joist-orm/build/newTestInstance.d.ts:26:46 - error TS2307: Cannot find module 'temporal-spec' or its corresponding type declarations.

26 export declare let testZonedDateTime: import("temporal-spec").Temporal.ZonedDateTime | undefined;
                                                ~~~~~~~~~~~~~~~
```

After adding both packages I was able to build. Do these need to be added as peer dependencies or to the docs?

**Comment by stephenh** [comment]
Thanks for filing :thinking: , we really thought those `import type`s would mean temporal wasn't actually a build/runtime dependency.

Out of curiosity, do you have `"skipLibCheck": true` enabled in your `tsconfig.json`? If not, maybe try that?

**Comment by davekerber** [comment]
It looks like if I set `"skipLibCheck": true,` it works. I'd rather not enable that. 

So it looks like they are only needed as dev dependencies then?

**Comment by stephenh** [comment]
You can add it as a `devDependency` yes; but that kinda sucks. In theory you shouldn't need to pull anything in unless you set the `temporal: true` flag and specifically opt-in to the new types.

Fwiw `skipLibCheck` is one of the 3 flags the recommended TS config enables (along with `strict` and `esModuleInterop`):

https://www.npmjs.com/package/@tsconfig/node20?activeTab=code

And personally it seems like I always run into some sort of library issue, that I end up enabling it.

So, dunno, personally would recommend that, but a `devDependency` is fine too ... I'll see what @zgavin thinks about making this even more optional, but it might be harder than its worth atm.

**Comment by davekerber** [comment]
> So, dunno, personally would recommend that, but a devDependency is fine too ... I'll see what @zgavin thinks about making this even more optional, but it might be harder than its worth atm.

No worries, I'm happy to install a couple dev dependencies if that's all that's needed. No need to do a lot of work just for me. I'm excited to try out the temporal stuff when I get time. 👍

**Comment by stephenh** [comment]
Cool, sounds goods!

If you're poking around at temporal, @zgavin also added date-fns/luxon/Ruby activesupport-style fluent methods to our activesupport:

https://github.com/homebound-team/activesupport/pull/15

:tada: :-)

**Comment by stephenh** [comment]
For now I've just added an FAQ entry about the "use `skipLibCheck` or `devDependency`"--we'll see if maybe this eventually gets abstracted out even further (or I suppose more likely is that we move to the real temporal dependency that will ship in browsers/node).
