### ISSUE TITLE
Auto-detect setDefault assumes double quotes

### ISSUE THREAD

**Issue by brudil** [joist-orm/joist-orm#1202]
Fun one working out why this wasn't working over in single quote land :)

Happy to PR. Wondering if it's worth inverting the flow here to do a single global regex matchAll to find usages and then match them to the DbMetadata or just adding an additional .includes for single quotes.

**Comment by stephenh** [comment]
Oh lol, that is funny.

It's been just long enough that I wrote the auto-detect code that I'm forgetting how your proposed inverted flow would work/be applicable, but it could work well, just not sure.

I am often in "a little too q&d mode" so would probably do another `.includes` :-), but really haven't looked at the code.

Would be great if you filed a PR; thanks!
