### ISSUE TITLE
chore: ci/ensure codegen is up to date

### ISSUE THREAD

**Issue by brudil** [joist-orm/joist-orm#1231]
Following on from the #1229 prettier check, it would be great to ensure within PRs that codegen files are correct. It's another lil gotcha that is nice to have automated.

I'll see what we're doing as we have our generated schema.graphql checked in, but validated for drift in a gha job.

edit: we do a `git diff --exit-code packages/zapdos-schema/schema.graphql` - will see if that works with directories.

**Comment by stephenh** [comment]
Ah! Yep, we have an internal "run codegen and make sure there are no diffs" check, albeit slightly coupled to our internal setup; it looks like:

```
      - run:
          name: Validate Codegen (upon failure, see "Show Codegen Diff" step)
          command: |
            docker-compose exec tests yarn migrate
            docker-compose exec tests yarn codegen
            docker cp "$(docker-compose ps -q tests)":/home/node/app/src ~/project

            # This will fail the build if any git-tracked file has changed
            # after the codegen runs
            git status
            git diff --exit-code
```

If that makes a GitHub-action/Joist-repo version of this easier.
