### ISSUE TITLE
Hooks can see invalid versions of entities

### ISSUE THREAD

**Issue by stephenh** [joist-orm/joist-orm#154]
I.e. a beforeCreate is passed an `Author` will all of the required fields as-is; but b/c the hook sees the entities before the validation rules have verified the types are correct, something like `author.name.startsWith` could actually fail.

Seems like we should pass the hooks a "more correct" version of the entity with the required fields turned to optional.

---

Note that we've solved this for validation rules, b/c the "required fields" rules run before other rules.

The wrinkle is that hooks run even before required-field rules b/c they can set defaults for fields.

**Comment by mmahalwy** [comment]
I know there's a lot of inspiration from ActiveRecord here. According to AR, `before_create` is called _after_ validations [are run](https://guides.rubyonrails.org/active_record_callbacks.html#creating-an-object)

```
3.1 Creating an Object
before_validation
after_validation
before_save
around_save
before_create
around_create
after_create
after_save
after_commit / after_rollback
```

We dont have a before/after validation hooks for joist, but I think we can in the future. Having option fields on `beforeCreate` now would be make more difficult to add validation hooks. Thoughts?

**Comment by stephenh** [comment]
Yeah, that's a good point, we could add a before/after validation that specifically see maybe-invalid entities, and then hopefully by the time before/after create/save are called, the entity is ensured to be valid...

Currently we're using before create/save specifically to apply defaults (b/c we don't have a validation hook), so we'd have to move them to validation hooks...but...that seems doable.

**Comment by stephenh** [comment]
Async derived fields have the same issue:

```
config.setAsyncDerivedField(
  "identifier",
  { identifier: {}, commitment: { changeOrders_ro: "identifier_ro" } },
  (changeOrder) => {
    const commitment = changeOrder.commitment.get;
    // Maybe we could know to only run this derived field if the commitment is unset
    if (!commitment) {
      return "";
    }
```

Now that we have field-level hints, maybe we could run only the required rules for the referenced fields, before invoking a field lambda.

**Comment by stephenh** [comment]
We've fixed this recently by detecting "TypeErrors that are ~very likely unset required fields" and rerunning the async fields after validation rules pass.
