### ISSUE TITLE
Feature: Support Codegen for  Time Without Zone

### ISSUE THREAD

**Issue by davekerber** [joist-orm/joist-orm#757]
When I try to codegen on a column that is of type `time without time zone` 

```bash
Error: Unexpected object: time without time zone
    at assertNever (/work/node_modules/joist-codegen/build/utils.js:12:11)
    at mapSimpleDbTypeToTypescriptType (/work/node_modules/joist-codegen/build/utils.js:120:13)
    at mapType (/work/node_modules/joist-codegen/build/EntityDbMetadata.js:490:24)
```

Not sure how to model this, probably as a Date?

**Comment by stephenh** [comment]
Huh! Looks like "time without time zone" is just hour-minute-second-milli?

This is probably a `PlainTime`:

https://tc39.es/proposal-temporal/docs/#Temporal-PlainTime

I've been really tempted to ignore the "this is only stage 3 / don't use in production" warnings on temporal and just start using it anyway, b/c I want PlainDate for `date` columns as well...

Without temporal...not sure what the best data structure is. Maybe just something custom?

Well damn, there are active commits on the temporal repo:

https://github.com/tc39/proposal-temporal/commits/main

That's encouraging... :crossed_fingers:

**Comment by brudil** [comment]
Happy to work on this as we're eying up a move to Temporal soon and have some wall time plain times.

It's perhaps a new semantic but how would we feel about making this temporal exclusive?

My thinking here is to essentially throw/error within codegen if we come across this in a non-temporal config. Otherwise this would involve implementing some sort of additional shape for non-temporal which seems unideal.

**Comment by stephenh** [comment]
> Happy to work on this as we're eying up a move to Temporal soon and have some wall time plain times.

Great!

> It's perhaps a new semantic but how would we feel about making this a temporal exclusive?

Agreed! I'm just fine with some of these edge-casey datetime formats requiring temporal, for the easiest lift on our side, and likely best DX for end-users as well.

**Comment by stephenh** [comment]
Happened to be poking at timestamp-/temporal related things in #1328 and so did this as a follow up (currently requires temporal). :tada:
